# Generated by Django 4.2.1 on 2025-03-11 11:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='Номер стола')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения заказа')),
                ('status', models.CharField(choices=[('В ожидании', 'В ожидании'), ('Оплачено', 'Оплачено'), ('Готово', 'Готово')], default='В ожидании', max_length=11, verbose_name='Статус заказа')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сумма')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Скидка в %')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='menu.menu', verbose_name='Код блюда')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
